name: ejelistview
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/images/xbox1.jpg
   - assets/images/xbox2.jpg
   - assets/images/xbox3.png
   - assets/images/xbox4.png
   - assets/images/xbox5.jpg
   - assets/images/xbox6.png
   - assets/images/xbox7.png
   - assets/images/xbox8.jpg
   - assets/images/xbox9.jpg
   - assets/images/xbox10.jpg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
